name: Java Bindings - Code Format

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - '**/*'
  push:
    branches:
      - 'main'
    paths:
      - '**/*'

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run format checker
        run: |
          bash scripts/java/gha/format/format.sh -check
