\name: Java Bindings - C++ UT

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ut-centos7:
    runs-on: ubuntu-latest
    env:
      HOST_CCACHE_DIR: "${{ github.workspace }}/.ccache"
    steps:
      - uses: actions/checkout@v4
      - name: Restore Ccache
        uses: actions/cache/restore@v4
        with:
          path: '${{ env.HOST_CCACHE_DIR }}'
          key: java-ut-cpp-ut-centos7-ccache-${{github.sha}}
          restore-keys: |
            java-ut-cpp-ut-centos7-ccache-
      - name: Run setup script / Build and run UTs
        run: |
          docker run -v ${{ github.workspace }}:/velox -w /velox centos:7 bash -c "
            export CCACHE_DIR=/velox/.ccache
            export CCACHE_MAXSIZE=3000M
            cd /velox/java/velox4j
            bash scripts/gha/ut-cpp/setup-centos7.sh
            bash src/main/cpp/test.sh
          "
      - name: Save Ccache
        uses: actions/cache/save@v4
        with:
          path: '${{ env.HOST_CCACHE_DIR }}'
          key: java-ut-cpp-ut-centos7-ccache-${{github.sha}}
